export const teamValues = {
  HOU: "Astros",
  TEX: "Rangers",
  CHC: "Cubs",
  MIL: "Brewers",
  CIN: "Reds",
  WSH: "Nationals",
  STL: "Cardinals",
  MIA: "Marlins",
  BAL: "Orioles",
  NYY: "Yankees",
  ATL: "Braves",
  CLE: "Guardians",
  KC: "Royals",
  MIN: "Twins",
  LAA: "Angles",
  SD: "Padres",
  SEA: "Mariners",
  SF: "Giants",
  PIT: "Pirates",
  LAD: "Dodgers",
  NYM: "Mets",
  PHI: "Phillies",
  CHW: "White Sox",
  OAK: "Athletics",
  TB: "Devil Rays",
  COL: "Rockies",
  TOR: "Blue Jays",
  ARI: "Diamondbacks",
  DET: "Tigers",
  BOS: "Red Sox",
};

export const monthsShort = {
  1: "JAN",
  2: "FEB",
  3: "MAR",
  4: "APR",
  5: "MAY",
  6: "JUN",
  7: "JUL",
  8: "AUG",
  9: "SEP",
  10: "OCT",
  11: "NOV",
  12: "DEC",
};
